framework:
    secret: '%env(APP_SECRET)%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: ['%locale%']
    csrf_protection: ~
    form: ~
    validation:
        enable_annotations: true
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        handler_id: ~
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    http_method_override: true
    assets: ~
    serializer:
        enable_annotations: true
    php_errors:
        log: true
