twig_component:
    anonymous_template_directory: components/
    defaults:
        EasyCorp\Bundle\EasyAdminBundle\Twig\Component\:
            template_directory: '@EasyAdmin/components/'
            name_prefix: 'ea'
