# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    #___________________________________________________________________________exception listener
    kernel.listener.acme_foo_exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        arguments: ["@templating", "@kernel"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    #___________________________________________________________________________flash message
    flash_messages:
        class: AppBundle\EventListener\FlashMessages
        arguments: [ '@session', '@translator' ]
        tags:
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove }
            - { name: doctrine.event_listener, event: postPersist }
        
    #___________________________________________________________________________#mouvements stock event listener
    #set qte article
    app.doctrine_set_qte_article_listener:
        class: AppBundle\EventListener\SetQteArticleListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    #add stock when br is added or updated if br is terminated
    #add stock if article is entred and stockable=true
    app.doctrine_add_stock_listener:
        class: AppBundle\EventListener\AddStockListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }
    #remove stock when bl is added or updated if bl is terminated
    #remove stock when facture is added or updated if facture is terminated
    app.doctrine_remove_stock_listener:
        class: AppBundle\EventListener\RemoveStockListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }
    #___________________________________________________________________________end mouvements stock event listener#
    #___________________________________________________________________________#mouvements financiers event listener
    #add or delete revenu when add or delete reglement bl
    #add or delete revenu when add or delete reglement facture
    app.doctrine_set_revenu_listener:
        class: AppBundle\EventListener\SetRevenuListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preRemove }
    #add or delete depense when add or delete reglement bon reception
    app.doctrine_set_depense_listener:
        class: AppBundle\EventListener\SetDepenseListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preRemove }
    #add automatic retenu a la source reglement
    #if we add facture,bon de reception or bon de livraison
    app.doctrine_retenu_a_la_source_listener:
        class: AppBundle\EventListener\RetenuAlaSourceListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }
    #if we add or update facture avoir
    app.doctrine_facture_avoir_listener:
        class: AppBundle\EventListener\FactureAvoirListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
    #___________________________________________________________________________end mouvements financiers event listener#
    #generate devis code or facture code
    app.doctrine_code_generator_listener:
        class: AppBundle\EventListener\CodeGeneratorListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    #set regle attribute of facture
    app.doctrine_set_regle_facture_listener:
        class: AppBundle\EventListener\SetRegleFactureListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preRemove }
    #set regle attribute of bon reception
    app.doctrine_set_regle_bon_reception_listener:
        class: AppBundle\EventListener\SetRegleBonReceptionListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preRemove }
    #set regle attribute of bon livraison
    app.doctrine_set_regle_bon_livraison_listener:
        class: AppBundle\EventListener\SetRegleBonLivraisonListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preRemove }
    #media listener
    app.doctrine_media_listener:
        class: AppBundle\EventListener\MediaListener
        arguments: ["%images_directory%"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: preRemove }
            - { name: doctrine.event_listener, event: postRemove }     
   
        
    your.user_login_route_listener:
        class: AppBundle\Event\UserLoginRouteListener
        arguments: ["@security.token_storage", "@router"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    my.subscriber:
        class: AppBundle\EventListener\SearchIndexerSubscriber
        arguments: ["@security.token_storage"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }
            
    app.format_date:
        class: AppBundle\Service\FormatDate
    app.notification_system:
        class: AppBundle\Service\NotificationSystem
        arguments: ["@doctrine.orm.entity_manager"]
    app.excel_custom_config:
        class: AppBundle\Service\ExcelCustomConfig
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
