operator_controllers:
    resource: '../src/Controller/Operator/'
    type: annotation
    host: 'admin.{domain}'
    defaults:
        domain: '%app.base_domain%'
    requirements:
        domain: '.+'

controllers:
    resource: '../src/Controller/'
    type: annotation
    exclude: '../src/Controller/Operator/'
