<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260615124342 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE article (id INT AUTO_INCREMENT NOT NULL, tva_id INT DEFAULT NULL, famille_id INT DEFAULT NULL, unite_id INT DEFAULT NULL, categorie_id INT DEFAULT NULL, sousfamille_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, media_id INT DEFAULT NULL, fournisseur_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, designation VARCHAR(255) DEFAULT NULL, prix_achat NUMERIC(10, 3) DEFAULT NULL, marge NUMERIC(10, 3) DEFAULT NULL, prix_vente_ht NUMERIC(10, 3) DEFAULT NULL, prix_vente_ttc NUMERIC(10, 3) DEFAULT NULL, stockable TINYINT(1) NOT NULL, service TINYINT(1) NOT NULL, qte_en_depart INT DEFAULT NULL, qte_en_stock INT DEFAULT NULL, seuil_alert INT DEFAULT NULL, date_ajout DATE DEFAULT NULL, note TEXT DEFAULT NULL, desactiver_photo TINYINT(1) DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), INDEX tva_id (tva_id), INDEX unite_id (unite_id), INDEX categorie_id (categorie_id), INDEX famille_id (famille_id), INDEX sousfamille_id (sousfamille_id), INDEX media_id (media_id), INDEX fournisseur_id (fournisseur_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE banque (id INT AUTO_INCREMENT NOT NULL, created_user_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX created_user_id (created_user_id), INDEX created_user_id_2 (created_user_id), INDEX updated_user_id (updated_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bon_commande_frs (id INT AUTO_INCREMENT NOT NULL, fournisseur_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, note TEXT DEFAULT NULL, termine TINYINT(1) NOT NULL, date_creation DATE DEFAULT NULL, date_commande DATE DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), INDEX fournisseur_id (fournisseur_id), UNIQUE INDEX code (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bon_livraison (id INT AUTO_INCREMENT NOT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, client_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, ht NUMERIC(10, 3) NOT NULL, remise NUMERIC(10, 3) NOT NULL, tva NUMERIC(10, 3) NOT NULL, total NUMERIC(10, 3) NOT NULL, taux_retenu NUMERIC(10, 3) NOT NULL, total_retenu NUMERIC(10, 3) NOT NULL, regle NUMERIC(10, 3) NOT NULL, reste NUMERIC(10, 3) NOT NULL, note TEXT DEFAULT NULL, termine TINYINT(1) NOT NULL, converted TINYINT(1) NOT NULL, date_creation DATE DEFAULT NULL, date_livraison DATE DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, nom VARCHAR(255) DEFAULT NULL, cin VARCHAR(255) DEFAULT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), INDEX client_id (client_id), UNIQUE INDEX code (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bon_reception (id INT AUTO_INCREMENT NOT NULL, bon_commande_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, fournisseur_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, ht NUMERIC(10, 3) NOT NULL, remise NUMERIC(10, 3) NOT NULL, tva NUMERIC(10, 3) NOT NULL, total NUMERIC(10, 3) NOT NULL, taux_retenu NUMERIC(10, 3) NOT NULL, total_retenu NUMERIC(10, 3) NOT NULL, regle NUMERIC(10, 3) NOT NULL, reste NUMERIC(10, 3) NOT NULL, note TEXT DEFAULT NULL, termine TINYINT(1) NOT NULL, date_reception DATE DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_C77F2B94B4B54061 (bon_commande_id), INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), INDEX fournisseur_id (fournisseur_id), UNIQUE INDEX code (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE categorie (id INT AUTO_INCREMENT NOT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), UNIQUE INDEX libelle (libelle), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client (id INT AUTO_INCREMENT NOT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, passager TINYINT(1) NOT NULL, status VARCHAR(255) NOT NULL, civilite VARCHAR(255) DEFAULT NULL, rs VARCHAR(255) DEFAULT NULL, mf VARCHAR(255) DEFAULT NULL, rc VARCHAR(255) DEFAULT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, adresse1 VARCHAR(255) DEFAULT NULL, adresse2 VARCHAR(255) DEFAULT NULL, adresse3 VARCHAR(255) DEFAULT NULL, code_postal VARCHAR(8) DEFAULT NULL, ville VARCHAR(255) DEFAULT NULL, pays VARCHAR(255) DEFAULT NULL, tel VARCHAR(255) DEFAULT NULL, mobile VARCHAR(255) DEFAULT NULL, fax VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, site_web VARCHAR(255) DEFAULT NULL, activite VARCHAR(255) DEFAULT NULL, remise NUMERIC(10, 0) NOT NULL, note TEXT DEFAULT NULL, total_avoir_rembourse NUMERIC(10, 3) NOT NULL, total_avoir_non_rembourse NUMERIC(10, 3) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), UNIQUE INDEX code (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE compte (id INT AUTO_INCREMENT NOT NULL, banque_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, rub VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX banque_id (banque_id), INDEX created_user_id (created_user_id), INDEX updated_user_id (updated_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE devis (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, ht NUMERIC(10, 3) NOT NULL, remise NUMERIC(10, 3) NOT NULL, tva NUMERIC(10, 3) NOT NULL, total NUMERIC(10, 3) NOT NULL, net_a_payer NUMERIC(10, 3) NOT NULL, note TEXT DEFAULT NULL, termine TINYINT(1) DEFAULT NULL, date_creation DATE DEFAULT NULL, date_validite DATE DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, nom VARCHAR(255) DEFAULT NULL, cin VARCHAR(255) DEFAULT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), INDEX client_id (client_id), UNIQUE INDEX code (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE facture (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, ht NUMERIC(10, 3) NOT NULL, remise NUMERIC(10, 3) NOT NULL, tva NUMERIC(10, 3) NOT NULL, total NUMERIC(10, 3) NOT NULL, timbre NUMERIC(10, 3) DEFAULT \'0.600\' NOT NULL, taux_retenu NUMERIC(10, 3) NOT NULL, total_retenu NUMERIC(10, 3) NOT NULL, total_avoir_rembourse NUMERIC(10, 3) NOT NULL, total_avoir_non_rembourse NUMERIC(10, 3) NOT NULL, benifice NUMERIC(10, 3) NOT NULL, regle NUMERIC(10, 3) NOT NULL, reste NUMERIC(10, 3) NOT NULL, note TEXT DEFAULT NULL, termine TINYINT(1) DEFAULT NULL, from_bl TINYINT(1) DEFAULT NULL, date_creation DATE DEFAULT NULL, date_echeance DATE DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, nom VARCHAR(255) DEFAULT NULL, cin VARCHAR(255) DEFAULT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), INDEX client_id (client_id), UNIQUE INDEX code (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE facture_avoir (id INT AUTO_INCREMENT NOT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, facture_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, ht NUMERIC(10, 3) NOT NULL, remise NUMERIC(10, 3) NOT NULL, tva NUMERIC(10, 3) NOT NULL, total NUMERIC(10, 3) NOT NULL, timbre NUMERIC(10, 3) DEFAULT \'0.000\' NOT NULL, benifice NUMERIC(10, 3) DEFAULT NULL, regle NUMERIC(10, 3) DEFAULT NULL, note TEXT DEFAULT NULL, termine TINYINT(1) NOT NULL, from_bl TINYINT(1) DEFAULT NULL, date_creation DATE DEFAULT NULL, date_echeance DATE DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), INDEX facture_id (facture_id), UNIQUE INDEX code (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE famille (id INT AUTO_INCREMENT NOT NULL, categorie_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_2473F213BCF5E72D (categorie_id), INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), UNIQUE INDEX libelle (libelle), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fournisseur (id INT AUTO_INCREMENT NOT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, rs VARCHAR(255) DEFAULT NULL, mf VARCHAR(255) DEFAULT NULL, rc VARCHAR(255) DEFAULT NULL, adresse1 VARCHAR(255) DEFAULT NULL, adresse2 VARCHAR(255) DEFAULT NULL, adresse3 VARCHAR(255) DEFAULT NULL, code_postal VARCHAR(8) DEFAULT NULL, ville VARCHAR(255) DEFAULT NULL, pays VARCHAR(255) DEFAULT NULL, tel VARCHAR(255) DEFAULT NULL, tel2 VARCHAR(255) DEFAULT NULL, mobile VARCHAR(255) DEFAULT NULL, fax VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, siteweb VARCHAR(255) DEFAULT NULL, note TEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), UNIQUE INDEX code (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_bon_commande_frs (id INT AUTO_INCREMENT NOT NULL, article_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, bon_commande_frs_id INT DEFAULT NULL, designation VARCHAR(255) NOT NULL, qte NUMERIC(10, 3) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), INDEX article_id (article_id), INDEX bon_commande_frs_id (bon_commande_frs_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_bon_livraison (id INT AUTO_INCREMENT NOT NULL, article_id INT DEFAULT NULL, tva_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, bon_livraison_id INT DEFAULT NULL, designation VARCHAR(255) NOT NULL, qte NUMERIC(10, 3) NOT NULL, prix_unitaire NUMERIC(10, 3) NOT NULL, remise NUMERIC(10, 3) NOT NULL, ttc NUMERIC(10, 3) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), INDEX article_id (article_id), INDEX tva_id (tva_id), INDEX bon_livraison_id (bon_livraison_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_bon_reception (id INT AUTO_INCREMENT NOT NULL, article_id INT DEFAULT NULL, tva_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, bon_reception_id INT DEFAULT NULL, designation VARCHAR(255) NOT NULL, qte NUMERIC(10, 3) NOT NULL, prix_unitaire NUMERIC(10, 3) NOT NULL, remise NUMERIC(10, 3) NOT NULL, ttc NUMERIC(10, 3) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), INDEX article_id (article_id), INDEX tva_id (tva_id), INDEX bon_reception_id (bon_reception_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_devis (id INT AUTO_INCREMENT NOT NULL, article_id INT DEFAULT NULL, tva_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, devis_id INT DEFAULT NULL, designation VARCHAR(255) DEFAULT NULL, qte NUMERIC(10, 3) NOT NULL, prix_unitaire NUMERIC(10, 3) NOT NULL, remise NUMERIC(10, 0) NOT NULL, ttc NUMERIC(10, 3) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_888B2F1B41DEFADA (devis_id), INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), INDEX article_id (article_id), INDEX tva_id (tva_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_facture (id INT AUTO_INCREMENT NOT NULL, article_id INT DEFAULT NULL, tva_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, facture_id INT DEFAULT NULL, designation VARCHAR(2000) DEFAULT NULL, qte NUMERIC(10, 3) NOT NULL, prix_unitaire NUMERIC(10, 3) NOT NULL, remise NUMERIC(10, 0) NOT NULL, ttc NUMERIC(10, 3) NOT NULL, benifice NUMERIC(10, 3) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_611F5A297F2DEE08 (facture_id), INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), INDEX article_id (article_id), INDEX tva_id (tva_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_facture_avoir (id INT AUTO_INCREMENT NOT NULL, article_id INT DEFAULT NULL, tva_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, facture_avoir_id INT DEFAULT NULL, designation VARCHAR(255) NOT NULL, qte NUMERIC(10, 3) NOT NULL, qte_max NUMERIC(10, 3) NOT NULL, prix_unitaire NUMERIC(10, 3) NOT NULL, remise NUMERIC(10, 3) NOT NULL, ttc NUMERIC(10, 3) NOT NULL, stock TINYINT(1) NOT NULL, reglement TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), INDEX article_id (article_id), INDEX tva_id (tva_id), INDEX facture_avoir_id (facture_avoir_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_reglement (id INT AUTO_INCREMENT NOT NULL, facture_id INT DEFAULT NULL, reglement_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, compte_id INT DEFAULT NULL, montant NUMERIC(10, 3) NOT NULL, date_reglement DATE DEFAULT NULL, date_echeance_cheque DATE DEFAULT NULL, num_cheque VARCHAR(255) DEFAULT NULL, date_echeance_traite DATE DEFAULT NULL, num_traite VARCHAR(255) DEFAULT NULL, type VARCHAR(255) NOT NULL, mode_reglement VARCHAR(255) NOT NULL, note TEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), INDEX facture_id (facture_id), INDEX reglement_id (reglement_id), INDEX mode_reglement (mode_reglement), INDEX updated_user_id_2 (updated_user_id), INDEX banque_rec_id (compte_id), INDEX compte_id (compte_id), INDEX compte_id_2 (compte_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_reglement_bon_livraison (id INT AUTO_INCREMENT NOT NULL, bon_livraison_id INT DEFAULT NULL, reglement_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, compte_id INT DEFAULT NULL, date_reglement DATE NOT NULL, montant NUMERIC(10, 3) NOT NULL, mode_reglement VARCHAR(255) NOT NULL, date_echeance_cheque DATE DEFAULT NULL, num_cheque VARCHAR(255) DEFAULT NULL, date_echeance_traite DATE DEFAULT NULL, num_traite VARCHAR(255) DEFAULT NULL, type VARCHAR(255) NOT NULL, note TEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), INDEX bon_livraison_id (bon_livraison_id), INDEX reglement_id (reglement_id), INDEX mode_reglement_id (mode_reglement), INDEX updated_user_id_2 (updated_user_id), INDEX banque_rec_id (compte_id), INDEX compte_id (compte_id), INDEX compte_id_2 (compte_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_reglement_bon_reception (id INT AUTO_INCREMENT NOT NULL, bon_reception_id INT DEFAULT NULL, reglement_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, compte_id INT DEFAULT NULL, date_reglement DATE NOT NULL, montant NUMERIC(10, 3) NOT NULL, mode_reglement VARCHAR(255) NOT NULL, date_echeance_cheque DATE DEFAULT NULL, num_cheque VARCHAR(255) DEFAULT NULL, date_echeance_traite DATE DEFAULT NULL, num_traite VARCHAR(255) DEFAULT NULL, type VARCHAR(255) NOT NULL, note TEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), INDEX bon_reception_id (bon_reception_id), INDEX reglement_id (reglement_id), INDEX mode_reglement_id (mode_reglement), INDEX updated_user_id_2 (updated_user_id), INDEX banque_rec_id (compte_id), INDEX compte_id (compte_id), INDEX compte_id_2 (compte_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE magasin (id INT AUTO_INCREMENT NOT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, adresse TEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), UNIQUE INDEX nom (nom), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE media (id INT AUTO_INCREMENT NOT NULL, created_user_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, path VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX created_user_id (created_user_id), INDEX updated_user_id (updated_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mode_reglement (id INT AUTO_INCREMENT NOT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), UNIQUE INDEX libelle (libelle), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mouvement (id INT AUTO_INCREMENT NOT NULL, compte_id INT DEFAULT NULL, client_id INT DEFAULT NULL, fournisseur_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, designation VARCHAR(255) NOT NULL, mouvement VARCHAR(255) NOT NULL, type_doc VARCHAR(255) DEFAULT NULL, tier VARCHAR(255) DEFAULT NULL, ttc NUMERIC(10, 3) NOT NULL, total_retenu NUMERIC(10, 3) NOT NULL, reglement_id INT DEFAULT NULL, mode_reglement VARCHAR(255) DEFAULT NULL, date_echeance DATE DEFAULT NULL, num_doc VARCHAR(255) DEFAULT NULL, etat VARCHAR(255) DEFAULT NULL, date_creation DATE DEFAULT NULL, note TEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_5B51FC3EF2C56620 (compte_id), INDEX client_id (client_id, fournisseur_id, updated_user_id, created_user_id), INDEX fournisseur_id (fournisseur_id), INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), INDEX IDX_5B51FC3E19EB6921 (client_id), UNIQUE INDEX reglement_id (reglement_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification (id INT AUTO_INCREMENT NOT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, description VARCHAR(255) NOT NULL, url TEXT NOT NULL, value_id INT NOT NULL, vu TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reglement (id INT AUTO_INCREMENT NOT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, total NUMERIC(10, 3) NOT NULL, reste NUMERIC(10, 3) NOT NULL, note TEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE retenu (id INT AUTO_INCREMENT NOT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, taux NUMERIC(10, 3) NOT NULL, montant NUMERIC(10, 3) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), UNIQUE INDEX taux (taux), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE societe (id INT AUTO_INCREMENT NOT NULL, media_id INT DEFAULT NULL, compte_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, rs VARCHAR(255) NOT NULL, mf VARCHAR(255) NOT NULL, rcs VARCHAR(255) NOT NULL, adresse VARCHAR(255) NOT NULL, ville VARCHAR(255) NOT NULL, pays VARCHAR(255) NOT NULL, code_postale VARCHAR(255) NOT NULL, tel VARCHAR(255) NOT NULL, fax VARCHAR(255) NOT NULL, mobile VARCHAR(255) NOT NULL, desactiver_photo TINYINT(1) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, site_web VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_19653DBDEA9FDD75 (media_id), UNIQUE INDEX UNIQ_19653DBDF2C56620 (compte_id), INDEX user_created_id (created_user_id), INDEX user_updated_id (updated_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sousfamille (id INT AUTO_INCREMENT NOT NULL, famille_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), INDEX famille_id (famille_id), INDEX famille_id_2 (famille_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stock (id INT AUTO_INCREMENT NOT NULL, article_id INT DEFAULT NULL, facture_id INT DEFAULT NULL, bon_livraison_id INT DEFAULT NULL, facture_avoir_id INT DEFAULT NULL, bon_reception_id INT DEFAULT NULL, client_id INT DEFAULT NULL, fournisseur_id INT DEFAULT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, designation VARCHAR(255) NOT NULL, type_doc VARCHAR(255) NOT NULL, qte NUMERIC(10, 3) NOT NULL, ttc NUMERIC(10, 3) NOT NULL, mouvement TINYINT(1) NOT NULL, note TEXT DEFAULT NULL, date_creation DATE DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_4B3656607F2DEE08 (facture_id), INDEX IDX_4B365660D8D16068 (bon_livraison_id), INDEX IDX_4B365660D192482A (facture_avoir_id), INDEX IDX_4B3656602A91441F (bon_reception_id), INDEX IDX_4B36566019EB6921 (client_id), INDEX updated_user_id (updated_user_id), INDEX updated_user_id_2 (updated_user_id), INDEX created_user_id (created_user_id), INDEX article_id (article_id), INDEX fournisseur_id (fournisseur_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE timbre (id INT AUTO_INCREMENT NOT NULL, valeur NUMERIC(10, 3) NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tva (id INT AUTO_INCREMENT NOT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, taux NUMERIC(10, 0) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX updated_user_id (updated_user_id), INDEX created_user_id (created_user_id), UNIQUE INDEX taux (taux), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE unite (id INT AUTO_INCREMENT NOT NULL, updated_user_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX updated_user_id (updated_user_id), INDEX updated_user_id_2 (updated_user_id), INDEX created_user_id (created_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_8D93D64992FC23A8 (username_canonical), UNIQUE INDEX UNIQ_8D93D649A0D96FBF (email_canonical), UNIQUE INDEX UNIQ_8D93D649C05FB297 (confirmation_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E664D79775F FOREIGN KEY (tva_id) REFERENCES tva (id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E6697A77B84 FOREIGN KEY (famille_id) REFERENCES famille (id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E66EC4A74AB FOREIGN KEY (unite_id) REFERENCES unite (id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E66BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E66C13231D6 FOREIGN KEY (sousfamille_id) REFERENCES sousfamille (id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E66BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E66E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E66EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E66670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id)');
        $this->addSql('ALTER TABLE banque ADD CONSTRAINT FK_B1F6CB3CE104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE banque ADD CONSTRAINT FK_B1F6CB3CBB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE bon_commande_frs ADD CONSTRAINT FK_36CBD96F670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id)');
        $this->addSql('ALTER TABLE bon_commande_frs ADD CONSTRAINT FK_36CBD96FBB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE bon_commande_frs ADD CONSTRAINT FK_36CBD96FE104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE bon_livraison ADD CONSTRAINT FK_31A531A4BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE bon_livraison ADD CONSTRAINT FK_31A531A4E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE bon_livraison ADD CONSTRAINT FK_31A531A419EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE bon_reception ADD CONSTRAINT FK_C77F2B94B4B54061 FOREIGN KEY (bon_commande_id) REFERENCES bon_commande_frs (id)');
        $this->addSql('ALTER TABLE bon_reception ADD CONSTRAINT FK_C77F2B94BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE bon_reception ADD CONSTRAINT FK_C77F2B94E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE bon_reception ADD CONSTRAINT FK_C77F2B94670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id)');
        $this->addSql('ALTER TABLE categorie ADD CONSTRAINT FK_497DD634BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE categorie ADD CONSTRAINT FK_497DD634E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE compte ADD CONSTRAINT FK_CFF6526037E080D9 FOREIGN KEY (banque_id) REFERENCES banque (id)');
        $this->addSql('ALTER TABLE compte ADD CONSTRAINT FK_CFF65260E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE compte ADD CONSTRAINT FK_CFF65260BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE devis ADD CONSTRAINT FK_8B27C52B19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE devis ADD CONSTRAINT FK_8B27C52BBB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE devis ADD CONSTRAINT FK_8B27C52BE104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT FK_FE86641019EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT FK_FE866410BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT FK_FE866410E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE facture_avoir ADD CONSTRAINT FK_F7AF92F4BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE facture_avoir ADD CONSTRAINT FK_F7AF92F4E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE facture_avoir ADD CONSTRAINT FK_F7AF92F47F2DEE08 FOREIGN KEY (facture_id) REFERENCES facture (id)');
        $this->addSql('ALTER TABLE famille ADD CONSTRAINT FK_2473F213BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id)');
        $this->addSql('ALTER TABLE famille ADD CONSTRAINT FK_2473F213BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE famille ADD CONSTRAINT FK_2473F213E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE fournisseur ADD CONSTRAINT FK_369ECA32BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE fournisseur ADD CONSTRAINT FK_369ECA32E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ligne_bon_commande_frs ADD CONSTRAINT FK_B27E79D07294869C FOREIGN KEY (article_id) REFERENCES article (id)');
        $this->addSql('ALTER TABLE ligne_bon_commande_frs ADD CONSTRAINT FK_B27E79D0BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ligne_bon_commande_frs ADD CONSTRAINT FK_B27E79D0E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ligne_bon_commande_frs ADD CONSTRAINT FK_B27E79D079862C75 FOREIGN KEY (bon_commande_frs_id) REFERENCES bon_commande_frs (id)');
        $this->addSql('ALTER TABLE ligne_bon_livraison ADD CONSTRAINT FK_3AC630C57294869C FOREIGN KEY (article_id) REFERENCES article (id)');
        $this->addSql('ALTER TABLE ligne_bon_livraison ADD CONSTRAINT FK_3AC630C54D79775F FOREIGN KEY (tva_id) REFERENCES tva (id)');
        $this->addSql('ALTER TABLE ligne_bon_livraison ADD CONSTRAINT FK_3AC630C5BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ligne_bon_livraison ADD CONSTRAINT FK_3AC630C5E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ligne_bon_livraison ADD CONSTRAINT FK_3AC630C5D8D16068 FOREIGN KEY (bon_livraison_id) REFERENCES bon_livraison (id)');
        $this->addSql('ALTER TABLE ligne_bon_reception ADD CONSTRAINT FK_CC1C2AF57294869C FOREIGN KEY (article_id) REFERENCES article (id)');
        $this->addSql('ALTER TABLE ligne_bon_reception ADD CONSTRAINT FK_CC1C2AF54D79775F FOREIGN KEY (tva_id) REFERENCES tva (id)');
        $this->addSql('ALTER TABLE ligne_bon_reception ADD CONSTRAINT FK_CC1C2AF5BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ligne_bon_reception ADD CONSTRAINT FK_CC1C2AF5E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ligne_bon_reception ADD CONSTRAINT FK_CC1C2AF52A91441F FOREIGN KEY (bon_reception_id) REFERENCES bon_reception (id)');
        $this->addSql('ALTER TABLE ligne_devis ADD CONSTRAINT FK_888B2F1B7294869C FOREIGN KEY (article_id) REFERENCES article (id)');
        $this->addSql('ALTER TABLE ligne_devis ADD CONSTRAINT FK_888B2F1B4D79775F FOREIGN KEY (tva_id) REFERENCES tva (id)');
        $this->addSql('ALTER TABLE ligne_devis ADD CONSTRAINT FK_888B2F1BBB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ligne_devis ADD CONSTRAINT FK_888B2F1BE104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ligne_devis ADD CONSTRAINT FK_888B2F1B41DEFADA FOREIGN KEY (devis_id) REFERENCES devis (id)');
        $this->addSql('ALTER TABLE ligne_facture ADD CONSTRAINT FK_611F5A297294869C FOREIGN KEY (article_id) REFERENCES article (id)');
        $this->addSql('ALTER TABLE ligne_facture ADD CONSTRAINT FK_611F5A294D79775F FOREIGN KEY (tva_id) REFERENCES tva (id)');
        $this->addSql('ALTER TABLE ligne_facture ADD CONSTRAINT FK_611F5A29BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ligne_facture ADD CONSTRAINT FK_611F5A29E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ligne_facture ADD CONSTRAINT FK_611F5A297F2DEE08 FOREIGN KEY (facture_id) REFERENCES facture (id)');
        $this->addSql('ALTER TABLE ligne_facture_avoir ADD CONSTRAINT FK_FCCC93957294869C FOREIGN KEY (article_id) REFERENCES article (id)');
        $this->addSql('ALTER TABLE ligne_facture_avoir ADD CONSTRAINT FK_FCCC93954D79775F FOREIGN KEY (tva_id) REFERENCES tva (id)');
        $this->addSql('ALTER TABLE ligne_facture_avoir ADD CONSTRAINT FK_FCCC9395BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ligne_facture_avoir ADD CONSTRAINT FK_FCCC9395E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ligne_facture_avoir ADD CONSTRAINT FK_FCCC9395D192482A FOREIGN KEY (facture_avoir_id) REFERENCES facture_avoir (id)');
        $this->addSql('ALTER TABLE ligne_reglement ADD CONSTRAINT FK_2401CEC47F2DEE08 FOREIGN KEY (facture_id) REFERENCES facture (id)');
        $this->addSql('ALTER TABLE ligne_reglement ADD CONSTRAINT FK_2401CEC46A477111 FOREIGN KEY (reglement_id) REFERENCES reglement (id)');
        $this->addSql('ALTER TABLE ligne_reglement ADD CONSTRAINT FK_2401CEC4BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ligne_reglement ADD CONSTRAINT FK_2401CEC4E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ligne_reglement ADD CONSTRAINT FK_2401CEC4F2C56620 FOREIGN KEY (compte_id) REFERENCES compte (id)');
        $this->addSql('ALTER TABLE ligne_reglement_bon_livraison ADD CONSTRAINT FK_F72EEB4D8D16068 FOREIGN KEY (bon_livraison_id) REFERENCES bon_livraison (id)');
        $this->addSql('ALTER TABLE ligne_reglement_bon_livraison ADD CONSTRAINT FK_F72EEB46A477111 FOREIGN KEY (reglement_id) REFERENCES reglement (id)');
        $this->addSql('ALTER TABLE ligne_reglement_bon_livraison ADD CONSTRAINT FK_F72EEB4BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ligne_reglement_bon_livraison ADD CONSTRAINT FK_F72EEB4E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ligne_reglement_bon_livraison ADD CONSTRAINT FK_F72EEB4F2C56620 FOREIGN KEY (compte_id) REFERENCES compte (id)');
        $this->addSql('ALTER TABLE ligne_reglement_bon_reception ADD CONSTRAINT FK_F9A8F4842A91441F FOREIGN KEY (bon_reception_id) REFERENCES bon_reception (id)');
        $this->addSql('ALTER TABLE ligne_reglement_bon_reception ADD CONSTRAINT FK_F9A8F4846A477111 FOREIGN KEY (reglement_id) REFERENCES reglement (id)');
        $this->addSql('ALTER TABLE ligne_reglement_bon_reception ADD CONSTRAINT FK_F9A8F484BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ligne_reglement_bon_reception ADD CONSTRAINT FK_F9A8F484E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ligne_reglement_bon_reception ADD CONSTRAINT FK_F9A8F484F2C56620 FOREIGN KEY (compte_id) REFERENCES compte (id)');
        $this->addSql('ALTER TABLE magasin ADD CONSTRAINT FK_54AF5F27BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE magasin ADD CONSTRAINT FK_54AF5F27E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10CE104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10CBB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE mode_reglement ADD CONSTRAINT FK_8C3AECF4BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE mode_reglement ADD CONSTRAINT FK_8C3AECF4E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE mouvement ADD CONSTRAINT FK_5B51FC3EF2C56620 FOREIGN KEY (compte_id) REFERENCES compte (id)');
        $this->addSql('ALTER TABLE mouvement ADD CONSTRAINT FK_5B51FC3E19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE mouvement ADD CONSTRAINT FK_5B51FC3E670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id)');
        $this->addSql('ALTER TABLE mouvement ADD CONSTRAINT FK_5B51FC3EBB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE mouvement ADD CONSTRAINT FK_5B51FC3EE104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CABB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAE104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE reglement ADD CONSTRAINT FK_EBE4C14CBB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE reglement ADD CONSTRAINT FK_EBE4C14CE104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE retenu ADD CONSTRAINT FK_D7AA08CEBB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE retenu ADD CONSTRAINT FK_D7AA08CEE104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE societe ADD CONSTRAINT FK_19653DBDEA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE societe ADD CONSTRAINT FK_19653DBDF2C56620 FOREIGN KEY (compte_id) REFERENCES compte (id)');
        $this->addSql('ALTER TABLE societe ADD CONSTRAINT FK_19653DBDE104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE societe ADD CONSTRAINT FK_19653DBDBB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE sousfamille ADD CONSTRAINT FK_D5FE76797A77B84 FOREIGN KEY (famille_id) REFERENCES famille (id)');
        $this->addSql('ALTER TABLE sousfamille ADD CONSTRAINT FK_D5FE767BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE sousfamille ADD CONSTRAINT FK_D5FE767E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE stock ADD CONSTRAINT FK_4B3656607294869C FOREIGN KEY (article_id) REFERENCES article (id)');
        $this->addSql('ALTER TABLE stock ADD CONSTRAINT FK_4B3656607F2DEE08 FOREIGN KEY (facture_id) REFERENCES facture (id)');
        $this->addSql('ALTER TABLE stock ADD CONSTRAINT FK_4B365660D8D16068 FOREIGN KEY (bon_livraison_id) REFERENCES bon_livraison (id)');
        $this->addSql('ALTER TABLE stock ADD CONSTRAINT FK_4B365660D192482A FOREIGN KEY (facture_avoir_id) REFERENCES facture_avoir (id)');
        $this->addSql('ALTER TABLE stock ADD CONSTRAINT FK_4B3656602A91441F FOREIGN KEY (bon_reception_id) REFERENCES bon_reception (id)');
        $this->addSql('ALTER TABLE stock ADD CONSTRAINT FK_4B36566019EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE stock ADD CONSTRAINT FK_4B365660670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id)');
        $this->addSql('ALTER TABLE stock ADD CONSTRAINT FK_4B365660BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE stock ADD CONSTRAINT FK_4B365660E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE tva ADD CONSTRAINT FK_EF699620BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE tva ADD CONSTRAINT FK_EF699620E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE unite ADD CONSTRAINT FK_1D64C118BB649746 FOREIGN KEY (updated_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE unite ADD CONSTRAINT FK_1D64C118E104C1D3 FOREIGN KEY (created_user_id) REFERENCES user (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E664D79775F');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E6697A77B84');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E66EC4A74AB');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E66BCF5E72D');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E66C13231D6');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E66BB649746');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E66E104C1D3');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E66EA9FDD75');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E66670C757F');
        $this->addSql('ALTER TABLE banque DROP FOREIGN KEY FK_B1F6CB3CE104C1D3');
        $this->addSql('ALTER TABLE banque DROP FOREIGN KEY FK_B1F6CB3CBB649746');
        $this->addSql('ALTER TABLE bon_commande_frs DROP FOREIGN KEY FK_36CBD96F670C757F');
        $this->addSql('ALTER TABLE bon_commande_frs DROP FOREIGN KEY FK_36CBD96FBB649746');
        $this->addSql('ALTER TABLE bon_commande_frs DROP FOREIGN KEY FK_36CBD96FE104C1D3');
        $this->addSql('ALTER TABLE bon_livraison DROP FOREIGN KEY FK_31A531A4BB649746');
        $this->addSql('ALTER TABLE bon_livraison DROP FOREIGN KEY FK_31A531A4E104C1D3');
        $this->addSql('ALTER TABLE bon_livraison DROP FOREIGN KEY FK_31A531A419EB6921');
        $this->addSql('ALTER TABLE bon_reception DROP FOREIGN KEY FK_C77F2B94B4B54061');
        $this->addSql('ALTER TABLE bon_reception DROP FOREIGN KEY FK_C77F2B94BB649746');
        $this->addSql('ALTER TABLE bon_reception DROP FOREIGN KEY FK_C77F2B94E104C1D3');
        $this->addSql('ALTER TABLE bon_reception DROP FOREIGN KEY FK_C77F2B94670C757F');
        $this->addSql('ALTER TABLE categorie DROP FOREIGN KEY FK_497DD634BB649746');
        $this->addSql('ALTER TABLE categorie DROP FOREIGN KEY FK_497DD634E104C1D3');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455BB649746');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455E104C1D3');
        $this->addSql('ALTER TABLE compte DROP FOREIGN KEY FK_CFF6526037E080D9');
        $this->addSql('ALTER TABLE compte DROP FOREIGN KEY FK_CFF65260E104C1D3');
        $this->addSql('ALTER TABLE compte DROP FOREIGN KEY FK_CFF65260BB649746');
        $this->addSql('ALTER TABLE devis DROP FOREIGN KEY FK_8B27C52B19EB6921');
        $this->addSql('ALTER TABLE devis DROP FOREIGN KEY FK_8B27C52BBB649746');
        $this->addSql('ALTER TABLE devis DROP FOREIGN KEY FK_8B27C52BE104C1D3');
        $this->addSql('ALTER TABLE facture DROP FOREIGN KEY FK_FE86641019EB6921');
        $this->addSql('ALTER TABLE facture DROP FOREIGN KEY FK_FE866410BB649746');
        $this->addSql('ALTER TABLE facture DROP FOREIGN KEY FK_FE866410E104C1D3');
        $this->addSql('ALTER TABLE facture_avoir DROP FOREIGN KEY FK_F7AF92F4BB649746');
        $this->addSql('ALTER TABLE facture_avoir DROP FOREIGN KEY FK_F7AF92F4E104C1D3');
        $this->addSql('ALTER TABLE facture_avoir DROP FOREIGN KEY FK_F7AF92F47F2DEE08');
        $this->addSql('ALTER TABLE famille DROP FOREIGN KEY FK_2473F213BCF5E72D');
        $this->addSql('ALTER TABLE famille DROP FOREIGN KEY FK_2473F213BB649746');
        $this->addSql('ALTER TABLE famille DROP FOREIGN KEY FK_2473F213E104C1D3');
        $this->addSql('ALTER TABLE fournisseur DROP FOREIGN KEY FK_369ECA32BB649746');
        $this->addSql('ALTER TABLE fournisseur DROP FOREIGN KEY FK_369ECA32E104C1D3');
        $this->addSql('ALTER TABLE ligne_bon_commande_frs DROP FOREIGN KEY FK_B27E79D07294869C');
        $this->addSql('ALTER TABLE ligne_bon_commande_frs DROP FOREIGN KEY FK_B27E79D0BB649746');
        $this->addSql('ALTER TABLE ligne_bon_commande_frs DROP FOREIGN KEY FK_B27E79D0E104C1D3');
        $this->addSql('ALTER TABLE ligne_bon_commande_frs DROP FOREIGN KEY FK_B27E79D079862C75');
        $this->addSql('ALTER TABLE ligne_bon_livraison DROP FOREIGN KEY FK_3AC630C57294869C');
        $this->addSql('ALTER TABLE ligne_bon_livraison DROP FOREIGN KEY FK_3AC630C54D79775F');
        $this->addSql('ALTER TABLE ligne_bon_livraison DROP FOREIGN KEY FK_3AC630C5BB649746');
        $this->addSql('ALTER TABLE ligne_bon_livraison DROP FOREIGN KEY FK_3AC630C5E104C1D3');
        $this->addSql('ALTER TABLE ligne_bon_livraison DROP FOREIGN KEY FK_3AC630C5D8D16068');
        $this->addSql('ALTER TABLE ligne_bon_reception DROP FOREIGN KEY FK_CC1C2AF57294869C');
        $this->addSql('ALTER TABLE ligne_bon_reception DROP FOREIGN KEY FK_CC1C2AF54D79775F');
        $this->addSql('ALTER TABLE ligne_bon_reception DROP FOREIGN KEY FK_CC1C2AF5BB649746');
        $this->addSql('ALTER TABLE ligne_bon_reception DROP FOREIGN KEY FK_CC1C2AF5E104C1D3');
        $this->addSql('ALTER TABLE ligne_bon_reception DROP FOREIGN KEY FK_CC1C2AF52A91441F');
        $this->addSql('ALTER TABLE ligne_devis DROP FOREIGN KEY FK_888B2F1B7294869C');
        $this->addSql('ALTER TABLE ligne_devis DROP FOREIGN KEY FK_888B2F1B4D79775F');
        $this->addSql('ALTER TABLE ligne_devis DROP FOREIGN KEY FK_888B2F1BBB649746');
        $this->addSql('ALTER TABLE ligne_devis DROP FOREIGN KEY FK_888B2F1BE104C1D3');
        $this->addSql('ALTER TABLE ligne_devis DROP FOREIGN KEY FK_888B2F1B41DEFADA');
        $this->addSql('ALTER TABLE ligne_facture DROP FOREIGN KEY FK_611F5A297294869C');
        $this->addSql('ALTER TABLE ligne_facture DROP FOREIGN KEY FK_611F5A294D79775F');
        $this->addSql('ALTER TABLE ligne_facture DROP FOREIGN KEY FK_611F5A29BB649746');
        $this->addSql('ALTER TABLE ligne_facture DROP FOREIGN KEY FK_611F5A29E104C1D3');
        $this->addSql('ALTER TABLE ligne_facture DROP FOREIGN KEY FK_611F5A297F2DEE08');
        $this->addSql('ALTER TABLE ligne_facture_avoir DROP FOREIGN KEY FK_FCCC93957294869C');
        $this->addSql('ALTER TABLE ligne_facture_avoir DROP FOREIGN KEY FK_FCCC93954D79775F');
        $this->addSql('ALTER TABLE ligne_facture_avoir DROP FOREIGN KEY FK_FCCC9395BB649746');
        $this->addSql('ALTER TABLE ligne_facture_avoir DROP FOREIGN KEY FK_FCCC9395E104C1D3');
        $this->addSql('ALTER TABLE ligne_facture_avoir DROP FOREIGN KEY FK_FCCC9395D192482A');
        $this->addSql('ALTER TABLE ligne_reglement DROP FOREIGN KEY FK_2401CEC47F2DEE08');
        $this->addSql('ALTER TABLE ligne_reglement DROP FOREIGN KEY FK_2401CEC46A477111');
        $this->addSql('ALTER TABLE ligne_reglement DROP FOREIGN KEY FK_2401CEC4BB649746');
        $this->addSql('ALTER TABLE ligne_reglement DROP FOREIGN KEY FK_2401CEC4E104C1D3');
        $this->addSql('ALTER TABLE ligne_reglement DROP FOREIGN KEY FK_2401CEC4F2C56620');
        $this->addSql('ALTER TABLE ligne_reglement_bon_livraison DROP FOREIGN KEY FK_F72EEB4D8D16068');
        $this->addSql('ALTER TABLE ligne_reglement_bon_livraison DROP FOREIGN KEY FK_F72EEB46A477111');
        $this->addSql('ALTER TABLE ligne_reglement_bon_livraison DROP FOREIGN KEY FK_F72EEB4BB649746');
        $this->addSql('ALTER TABLE ligne_reglement_bon_livraison DROP FOREIGN KEY FK_F72EEB4E104C1D3');
        $this->addSql('ALTER TABLE ligne_reglement_bon_livraison DROP FOREIGN KEY FK_F72EEB4F2C56620');
        $this->addSql('ALTER TABLE ligne_reglement_bon_reception DROP FOREIGN KEY FK_F9A8F4842A91441F');
        $this->addSql('ALTER TABLE ligne_reglement_bon_reception DROP FOREIGN KEY FK_F9A8F4846A477111');
        $this->addSql('ALTER TABLE ligne_reglement_bon_reception DROP FOREIGN KEY FK_F9A8F484BB649746');
        $this->addSql('ALTER TABLE ligne_reglement_bon_reception DROP FOREIGN KEY FK_F9A8F484E104C1D3');
        $this->addSql('ALTER TABLE ligne_reglement_bon_reception DROP FOREIGN KEY FK_F9A8F484F2C56620');
        $this->addSql('ALTER TABLE magasin DROP FOREIGN KEY FK_54AF5F27BB649746');
        $this->addSql('ALTER TABLE magasin DROP FOREIGN KEY FK_54AF5F27E104C1D3');
        $this->addSql('ALTER TABLE media DROP FOREIGN KEY FK_6A2CA10CE104C1D3');
        $this->addSql('ALTER TABLE media DROP FOREIGN KEY FK_6A2CA10CBB649746');
        $this->addSql('ALTER TABLE mode_reglement DROP FOREIGN KEY FK_8C3AECF4BB649746');
        $this->addSql('ALTER TABLE mode_reglement DROP FOREIGN KEY FK_8C3AECF4E104C1D3');
        $this->addSql('ALTER TABLE mouvement DROP FOREIGN KEY FK_5B51FC3EF2C56620');
        $this->addSql('ALTER TABLE mouvement DROP FOREIGN KEY FK_5B51FC3E19EB6921');
        $this->addSql('ALTER TABLE mouvement DROP FOREIGN KEY FK_5B51FC3E670C757F');
        $this->addSql('ALTER TABLE mouvement DROP FOREIGN KEY FK_5B51FC3EBB649746');
        $this->addSql('ALTER TABLE mouvement DROP FOREIGN KEY FK_5B51FC3EE104C1D3');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CABB649746');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAE104C1D3');
        $this->addSql('ALTER TABLE reglement DROP FOREIGN KEY FK_EBE4C14CBB649746');
        $this->addSql('ALTER TABLE reglement DROP FOREIGN KEY FK_EBE4C14CE104C1D3');
        $this->addSql('ALTER TABLE retenu DROP FOREIGN KEY FK_D7AA08CEBB649746');
        $this->addSql('ALTER TABLE retenu DROP FOREIGN KEY FK_D7AA08CEE104C1D3');
        $this->addSql('ALTER TABLE societe DROP FOREIGN KEY FK_19653DBDEA9FDD75');
        $this->addSql('ALTER TABLE societe DROP FOREIGN KEY FK_19653DBDF2C56620');
        $this->addSql('ALTER TABLE societe DROP FOREIGN KEY FK_19653DBDE104C1D3');
        $this->addSql('ALTER TABLE societe DROP FOREIGN KEY FK_19653DBDBB649746');
        $this->addSql('ALTER TABLE sousfamille DROP FOREIGN KEY FK_D5FE76797A77B84');
        $this->addSql('ALTER TABLE sousfamille DROP FOREIGN KEY FK_D5FE767BB649746');
        $this->addSql('ALTER TABLE sousfamille DROP FOREIGN KEY FK_D5FE767E104C1D3');
        $this->addSql('ALTER TABLE stock DROP FOREIGN KEY FK_4B3656607294869C');
        $this->addSql('ALTER TABLE stock DROP FOREIGN KEY FK_4B3656607F2DEE08');
        $this->addSql('ALTER TABLE stock DROP FOREIGN KEY FK_4B365660D8D16068');
        $this->addSql('ALTER TABLE stock DROP FOREIGN KEY FK_4B365660D192482A');
        $this->addSql('ALTER TABLE stock DROP FOREIGN KEY FK_4B3656602A91441F');
        $this->addSql('ALTER TABLE stock DROP FOREIGN KEY FK_4B36566019EB6921');
        $this->addSql('ALTER TABLE stock DROP FOREIGN KEY FK_4B365660670C757F');
        $this->addSql('ALTER TABLE stock DROP FOREIGN KEY FK_4B365660BB649746');
        $this->addSql('ALTER TABLE stock DROP FOREIGN KEY FK_4B365660E104C1D3');
        $this->addSql('ALTER TABLE tva DROP FOREIGN KEY FK_EF699620BB649746');
        $this->addSql('ALTER TABLE tva DROP FOREIGN KEY FK_EF699620E104C1D3');
        $this->addSql('ALTER TABLE unite DROP FOREIGN KEY FK_1D64C118BB649746');
        $this->addSql('ALTER TABLE unite DROP FOREIGN KEY FK_1D64C118E104C1D3');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE banque');
        $this->addSql('DROP TABLE bon_commande_frs');
        $this->addSql('DROP TABLE bon_livraison');
        $this->addSql('DROP TABLE bon_reception');
        $this->addSql('DROP TABLE categorie');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE compte');
        $this->addSql('DROP TABLE devis');
        $this->addSql('DROP TABLE facture');
        $this->addSql('DROP TABLE facture_avoir');
        $this->addSql('DROP TABLE famille');
        $this->addSql('DROP TABLE fournisseur');
        $this->addSql('DROP TABLE ligne_bon_commande_frs');
        $this->addSql('DROP TABLE ligne_bon_livraison');
        $this->addSql('DROP TABLE ligne_bon_reception');
        $this->addSql('DROP TABLE ligne_devis');
        $this->addSql('DROP TABLE ligne_facture');
        $this->addSql('DROP TABLE ligne_facture_avoir');
        $this->addSql('DROP TABLE ligne_reglement');
        $this->addSql('DROP TABLE ligne_reglement_bon_livraison');
        $this->addSql('DROP TABLE ligne_reglement_bon_reception');
        $this->addSql('DROP TABLE magasin');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE mode_reglement');
        $this->addSql('DROP TABLE mouvement');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE reglement');
        $this->addSql('DROP TABLE retenu');
        $this->addSql('DROP TABLE societe');
        $this->addSql('DROP TABLE sousfamille');
        $this->addSql('DROP TABLE stock');
        $this->addSql('DROP TABLE timbre');
        $this->addSql('DROP TABLE tva');
        $this->addSql('DROP TABLE unite');
        $this->addSql('DROP TABLE user');
    }
}
