<?php

namespace App\Doctrine;

use Doctrine\DBAL\Connection;

/**
 * DBAL connection wrapper used by the "tenant" entity manager.
 *
 * All tenant databases live on the same MySQL server with the same
 * credentials, so switching tenants is a matter of issuing `USE <db>` on the
 * connection. The target database is set by {@see selectDatabase()} (from the
 * TenantResolver on web requests, or from the provisioning/migration commands
 * on the CLI).
 *
 * The {@see connect()} override re-applies the `USE` after every (re)connect,
 * so the right database stays selected even if the underlying connection is
 * dropped and re-established mid-request.
 */
class TenantConnection extends Connection
{
    private ?string $tenantDatabase = null;

    /**
     * Point this connection at the given tenant database. Applies immediately
     * if already connected; otherwise it is applied on the next connect.
     */
    public function selectDatabase(string $dbName): void
    {
        $dbName = $this->sanitize($dbName);

        if ($dbName === $this->tenantDatabase) {
            return;
        }

        $this->tenantDatabase = $dbName;

        if ($this->isConnected()) {
            $this->useDatabase($dbName);
        }
    }

    public function getTenantDatabase(): ?string
    {
        return $this->tenantDatabase;
    }

    public function connect()
    {
        $wasConnected = $this->isConnected();
        $result = parent::connect();

        if (! $wasConnected && $this->tenantDatabase !== null) {
            $this->useDatabase($this->tenantDatabase);
        }

        return $result;
    }

    private function useDatabase(string $dbName): void
    {
        $this->executeStatement('USE `' . $dbName . '`');
    }

    private function sanitize(string $dbName): string
    {
        // Database names are generated by us (tenant_<slug>), but strip
        // backticks defensively before interpolating into `USE`.
        return str_replace('`', '', $dbName);
    }
}
